# Data Time Series

In [1]:
import numpy as np
import pandas as pd

## Load data

In [2]:
df_passenger = pd.read_csv('https://raw.githubusercontent.com/dhamvi01/Univariate-Time-Series-using-LSTM/master/airline-passengers.csv')
df_passenger

Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

In [3]:
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
    # find the end of this pattern
        end_ix = i + n_steps

    # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
    # gather input and output parts of the pattern
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
    return X, y


In [4]:
df_passenger.shape

(144, 2)

In [5]:
new= df_passenger['Passengers'].values

In [6]:
new

array([112, 118, 132, 129, 121, 135, 148, 148, 136, 119, 104, 118, 115,
       126, 141, 135, 125, 149, 170, 170, 158, 133, 114, 140, 145, 150,
       178, 163, 172, 178, 199, 199, 184, 162, 146, 166, 171, 180, 193,
       181, 183, 218, 230, 242, 209, 191, 172, 194, 196, 196, 236, 235,
       229, 243, 264, 272, 237, 211, 180, 201, 204, 188, 235, 227, 234,
       264, 302, 293, 259, 229, 203, 229, 242, 233, 267, 269, 270, 315,
       364, 347, 312, 274, 237, 278, 284, 277, 317, 313, 318, 374, 413,
       405, 355, 306, 271, 306, 315, 301, 356, 348, 355, 422, 465, 467,
       404, 347, 305, 336, 340, 318, 362, 348, 363, 435, 491, 505, 404,
       359, 310, 337, 360, 342, 406, 396, 420, 472, 548, 559, 463, 407,
       362, 405, 417, 391, 419, 461, 472, 535, 622, 606, 508, 461, 390,
       432])

In [7]:
# transform univariate time series to supervised learning problem
from numpy import array
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
    # find the end of this pattern
        end_ix = i + n_steps
    # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
    # gather input and output parts of the pattern
        # print(i, end_ix)
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

X, y = split_sequence(new, 3)


In [8]:
df_X = pd.DataFrame(X, columns=['Xt-2', 'Xt-1', 'Xt'])
df_y = pd.DataFrame(y, columns=['y'])

In [9]:
df_X.head()

Xt-2  Xt-1   Xt
0   112   118  132
1   118   132  129
2   132   129  121
3   129   121  135
4   121   135  148

In [10]:
df_X.shape

(141, 3)

In [11]:
X= df_X.iloc[:,0:2]
y= df_X.iloc[:,-1]

In [12]:
y

0      132
1      129
2      121
3      135
4      148
      ... 
136    622
137    606
138    508
139    461
140    390
Name: Xt, Length: 141, dtype: int64

## Normalisasi

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
X_norm= scaler.fit_transform(X)
y_norm= scaler.fit_transform(y.values.reshape(-1,1))

In [14]:
y_norm

array([[0.05405405],
       [0.04826255],
       [0.03281853],
       [0.05984556],
       [0.08494208],
       [0.08494208],
       [0.06177606],
       [0.02895753],
       [0.        ],
       [0.02702703],
       [0.02123552],
       [0.04247104],
       [0.07142857],
       [0.05984556],
       [0.04054054],
       [0.08687259],
       [0.12741313],
       [0.12741313],
       [0.1042471 ],
       [0.05598456],
       [0.01930502],
       [0.06949807],
       [0.07915058],
       [0.08880309],
       [0.14285714],
       [0.11389961],
       [0.13127413],
       [0.14285714],
       [0.18339768],
       [0.18339768],
       [0.15444015],
       [0.11196911],
       [0.08108108],
       [0.11969112],
       [0.12934363],
       [0.14671815],
       [0.17181467],
       [0.14864865],
       [0.15250965],
       [0.22007722],
       [0.24324324],
       [0.26640927],
       [0.2027027 ],
       [0.16795367],
       [0.13127413],
       [0.17374517],
       [0.17760618],
       [0.177

In [15]:
X_norm

array([[0.01544402, 0.02702703],
       [0.02702703, 0.05405405],
       [0.05405405, 0.04826255],
       [0.04826255, 0.03281853],
       [0.03281853, 0.05984556],
       [0.05984556, 0.08494208],
       [0.08494208, 0.08494208],
       [0.08494208, 0.06177606],
       [0.06177606, 0.02895753],
       [0.02895753, 0.        ],
       [0.        , 0.02702703],
       [0.02702703, 0.02123552],
       [0.02123552, 0.04247104],
       [0.04247104, 0.07142857],
       [0.07142857, 0.05984556],
       [0.05984556, 0.04054054],
       [0.04054054, 0.08687259],
       [0.08687259, 0.12741313],
       [0.12741313, 0.12741313],
       [0.12741313, 0.1042471 ],
       [0.1042471 , 0.05598456],
       [0.05598456, 0.01930502],
       [0.01930502, 0.06949807],
       [0.06949807, 0.07915058],
       [0.07915058, 0.08880309],
       [0.08880309, 0.14285714],
       [0.14285714, 0.11389961],
       [0.11389961, 0.13127413],
       [0.13127413, 0.14285714],
       [0.14285714, 0.18339768],
       [0.

In [16]:
# import split_dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_norm, y_norm, test_size=0.2, random_state=0)

## Training data

In [17]:
# import knn
from sklearn.neighbors import KNeighborsRegressor
model_knn = KNeighborsRegressor(n_neighbors=3)
model_knn.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [18]:
y_pred=model_knn.predict(X_test)

In [19]:
y_pred=pd.DataFrame(y_pred, columns=['y_pred'])

In [20]:
y_test=pd.DataFrame(y_test, columns=['y_test'])

In [21]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

0.006128763185080589

In [22]:
type(y_test)

pandas.core.frame.DataFrame

In [23]:
type(y_pred)

pandas.core.frame.DataFrame

In [24]:
df_y_test = pd.DataFrame(y_test,columns=['y_test'])
df_y_pred = pd.DataFrame(y_pred,columns=['y_pred'])

df = pd.concat([df_y_test, df_y_pred], axis=1)

In [25]:
df

y_test    y_pred
0   0.173745  0.115187
1   0.252896  0.143501
2   0.028958  0.040541
3   0.268340  0.268983
4   0.299228  0.377735
5   0.142857  0.167310
6   0.249035  0.273488
7   0.256757  0.379665
8   0.710425  0.575933
9   0.000000  0.072072
10  0.501931  0.391892
11  0.127413  0.076577
12  0.878378  0.784427
13  0.610039  0.548906
14  0.857143  0.728443
15  0.484556  0.494852
16  0.447876  0.366795
17  0.333977  0.379665
18  0.119691  0.045689
19  0.146718  0.220077
20  0.389961  0.455598
21  0.079151  0.064350
22  0.969112  0.824324
23  0.142857  0.078507
24  0.032819  0.062420
25  0.638996  0.524453
26  0.131274  0.094595
27  0.563707  0.627413
28  0.104247  0.167310

In [26]:
df.to_excel('df_y.xlsx', index=False)

In [27]:
y.min()

104

In [28]:
y.max()

622

In [29]:
y_pred

y_pred
0   0.115187
1   0.143501
2   0.040541
3   0.268983
4   0.377735
5   0.167310
6   0.273488
7   0.379665
8   0.575933
9   0.072072
10  0.391892
11  0.076577
12  0.784427
13  0.548906
14  0.728443
15  0.494852
16  0.366795
17  0.379665
18  0.045689
19  0.220077
20  0.455598
21  0.064350
22  0.824324
23  0.078507
24  0.062420
25  0.524453
26  0.094595
27  0.627413
28  0.167310